# Generated by Django 4.2.6 on 2023-11-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control_de_datos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilotos',
            name='biografia',
            field=models.TextField(blank=True),
        ),
    ]
