# Generated by Django 4.2.6 on 2023-11-26 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control_de_datos', '0002_pilotos_biografia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilotos',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='pilotos_photos/'),
        ),
    ]
